services:
  app:
    image: node:18
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 3080:3000
    command: bash -c "yarn install && yarn prisma generate && yarn build && yarn start:prod"
